spring:
  application:
    name: graphql-todo-app
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
graphiql:
  enabled: true
